server:
  port: 8887
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?characterEnconding=UTF8&socketTimeout=60000
    username: root
    password: root

  #thymeleaf ”ÕºΩ‚Œˆ∆˜
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
