server:
  port: 8887
  servlet:
    context-path: /
#参数配置
github:
  accesstoken:
    client_id: 2263f7d8276928e147d0
    client_secret: 2abacbb12febb6e407a812811d8b30237e7b018a
    redirect_uri: http://localhost:8887/callback
    access_token_url: https://github.com/login/oauth/access_token
    get_github_user_url: https://api.github.com/user?access_token=
spring:
  datasource:
    #mysql
#    url: jdbc:mysql://localhost:3306/community?characterEnconding=UTF8&socketTimeout=60000
#    username: root
#    #password: root
#    password: 123456
    #H2
    url: jdbc:h2:~/community
    username: sa
    password: 123
    driver-class-name: org.h2.Driver

  #thymeleaf视图解析器

  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML